spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

service:
  order:
    url: ${SERVICE_ORDER_URL:http://order-service:8081}
  product:
    url: ${SERVICE_PRODUCT_URL:http://product-service:8082}
  payment:
    url: ${SERVICE_PAYMENT_URL:http://payment-service:8083}