spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

service:
  product:
    url: ${SERVICE_PRODUCT_URL:http://product-service:8082}
  order:
    url: ${SERVICE_ORDER_URL:http://order-service:8081}